spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timeline?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: timeline
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    # schema:
      # - classpath: user.sql