spring:
  datasource:
    url: jdbc:mysql://localhost:3306/timeline?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    username: timeline
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
#      schema:
#          - classpath: user.sql

server:
  port: 8080